version: '3'

services:
  server:
    container_name: bot
    build: '.'
    depends_on:
      - db
    links:
      - db

  db:
    image: 'mongo:latest'
    container_name: mongo_bot
    ports:
      - '27018:27017'
    volumes:
      - /data/db:/data/db